### ISSUE TITLE
contextual data not in plots

### ISSUE THREAD

**Issue by abissett** [BioplatformsAustralia/bpaotu#224] opened 2022-07-05 05:55 UTC
When I search for soil, bacteria, calcium between 0 and 1000, the calcium plot doesn't get plotted

![image](https://user-images.githubusercontent.com/8981775/177258942-45a5afc3-19a1-4690-af87-67d7b75a5a1c.png)

**Comment by hou098** [comment] 2022-07-06 04:23
Could not reproduce, so most likely some kind of race condition. It might be showing a plot for a previous search, and not refreshing for the latest search results.

If this happens again, try switching to another tab (e.g. taxonomy) and back again. If that shows the ``Exc calcium`` button, that would lend weight to that refresh theory.

This _might_ be fixed by the fix for https://github.com/BioplatformsAustralia/bpaotu/issues/221 which is dealing with a similar problem and the same section of code.

**Comment by hou098** [comment] 2022-07-19 03:00
May be fixed by https://github.com/BioplatformsAustralia/bpaotu/commit/76865a57b27c2d292cd07aced11425100da824ef

**Closed** 2023-07-19 00:17 UTC
Labels: bug
